# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os:
  - linux
  - osx

r:
  - 3.2
  - 3.3
  - 3.4
  - oldrel

after_success:
  - Rscript -e 'covr::codecov()'

# osx for devel have issues to install devtools
matrix:
  include:
  - r: devel
    os: linux
  - r: release
    os: linux
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: release
    os: osx
